### ISSUE TITLE
pynk2_test_file.py is missing in source package

### ISSUE THREAD

**Issue by vwegert** [libyal/libnk2#4]
Similar to [this](https://github.com/libyal/libfwnt/issues/12) and [this](https://github.com/libyal/libwrc/issues/1) issue: The file `tests/pynk2_test_file.py` is present in the main Git repository, but missing in the released source packages. This causes the test to fail when run with `make check`. Manually adding the file from the master repository fixes the issue locally.

**Comment by joachimmetz** [comment]
File already included in tests/Makefile.am issue should be solved in next release https://github.com/libyal/libnk2/blob/main/tests/Makefile.am#L35
